<a href="https://colab.research.google.com/github/cjharsh/Colab-Files-with-ML/blob/master/GLA_lab_ML_2_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [0]:
a = array([[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]])

In [0]:
print(a)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]]


In [0]:
M = mean(a.T, axis=1)

In [0]:
M

array([3.5, 4.5])

In [0]:
c = a-M
print(c)

[[-2.5 -2.5]
 [-1.5 -1.5]
 [-0.5 -0.5]
 [ 0.5  0.5]
 [ 1.5  1.5]
 [ 2.5  2.5]]


In [0]:
#covaraince
V = cov(c.T)
print(V)

[[3.5 3.5]
 [3.5 3.5]]


In [0]:
#eigen values eigen vectors
values, vectors = eig(V)
print(values)
print(vectors)

[7. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [0]:
p = vectors.T.dot(c.T)
print(p)

[[-3.53553391 -2.12132034 -0.70710678  0.70710678  2.12132034  3.53553391]
 [ 0.          0.          0.          0.          0.          0.        ]]
